import { Code2, FileJson, Plus, Upload, X } from 'lucide-react';
import type { Node } from '@xyflow/react';
import type { RegistryNode } from '../../../shared/types';
import { PortEditor } from './PortEditor';
import type { useCustomNodeBuilder } from './useCustomNodeBuilder';
export function BuilderSections({ m, workflowNodes }: {
    m: ReturnType<typeof useCustomNodeBuilder>;
    workflowNodes: Node[];
    registry: RegistryNode[];
}) { return <div className="custom-node-builder-grid"><section className="custom-node-builder-column"><div className="section-title">۱. Inputs</div><div className="custom-builder-column-body"><div className="custom-source-picker workflow-shell-card"><b>ساخت ورودی از خروجی نودهای Workflow</b><select value={m.sourceNodeId} onChange={(e) => m.setSourceNodeId(e.target.value)}><option value="">انتخاب نود...</option>{workflowNodes.map((node) => <option key={node.id} value={node.id}>{String(node.data?.label || node.id)}</option>)}</select><select value={m.sourcePortId} onChange={(e) => m.setSourcePortId(e.target.value)} disabled={!m.sourceDefinition}><option value="">انتخاب خروجی...</option>{m.sourceDefinition?.outputs.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.type}</option>)}</select><button className="tiny-action" type="button" disabled={!m.sourceDefinition || !m.sourcePortId} onClick={m.addSourcePort}><Plus size={13}/> تبدیل به input port</button><small>اتصال واقعی بعداً با drag کردن نود و وصل‌کردن پورت‌ها انجام می‌شود.</small></div><PortEditor title="Input ports" ports={m.inputs} onChange={m.setInputs} kind="input"/><div className="custom-template-box workflow-shell-card"><b><FileJson size={17}/> Template ورودی</b><span>CSV یا JSON برای تعریف نمونه ورودی و تست کد؛ حداکثر 512KB.</span><input ref={m.fileRef} type="file" accept=".csv,.json,text/csv,application/json" hidden onChange={(e) => { const file = e.target.files?.[0]; if (file)
    void m.upload(file); e.currentTarget.value = ''; }}/><button className="tiny-action" type="button" onClick={() => m.fileRef.current?.click()}><Upload size={13}/> آپلود template</button>{m.template && <div className="custom-template-summary"><code>{String(m.template.filename || m.template.format || 'template')}</code><button className="tiny-action icon-action" type="button" onClick={() => m.setTemplate(null)}><X size={12}/></button></div>}</div></div></section><section className="custom-node-builder-column custom-code-column"><div className="section-title">۲. Python settings</div><div className="custom-builder-column-body"><div className="custom-code-help"><Code2 size={15}/><span><code>inputs</code> یک dict بر اساس شناسه input port است. نتیجه می‌تواند یک مقدار یا dict بر اساس شناسه output port باشد.</span></div><textarea className="custom-code-editor" spellCheck={false} value={m.code} onChange={(e) => m.setCode(e.target.value)}/><pre className="custom-code-example">{`# Example\nimport pandas as pd\ndf = pd.DataFrame(inputs["input"])\ndf["total"] = df.select_dtypes("number").sum(axis=1)\nreturn {"output": df}`}</pre></div></section><section className="custom-node-builder-column"><div className="section-title">۳. Outputs</div><div className="custom-builder-column-body"><PortEditor title="Output ports" ports={m.outputs} onChange={m.setOutputs} kind="output"/><div className="custom-output-note">برای خروجی جدول، نوع <code>dataframe</code> را انتخاب و DataFrame یا آرایه‌ای از objectها برگردانید.</div></div></section></div>; }
