import type { CSSProperties } from 'react';
export type WorkflowHeaderProps = {
    floatingTopbarStyle: CSSProperties;
    topbarLeftStyle: CSSProperties;
    topbarCenterStyle: CSSProperties;
    topbarRightStyle: CSSProperties;
    onLogout: () => void;
    onProfile: () => void;
    onAdmin: () => void;
    showAdmin: boolean;
    onProjects: () => void;
    onCancelRun: () => void;
    runActive: boolean;
    onExport: () => void;
    onLayout: () => void;
    onCreateComponent: () => void;
    createComponentDisabled: boolean;
    readOnly: boolean;
    runDisabled: boolean;
    runSelectedNode: boolean;
    runBusy: boolean;
    onRun: () => void;
    boardOpen: boolean;
    onToggleBoard: () => void;
    saveDisabled: boolean;
    versionBusy: boolean;
    onSaveVersion: () => void;
    onRenameBoard: () => void;
    onDeleteBoard: () => void;
    activeBoardIsMain: boolean;
    autosaveState: string;
    autosaveUpdatedAt: string | null;
    autosaveLabel: string;
    projectName: string;
    workflowName: string;
    onProject: () => void;
};
