import type { SetStateAction } from 'react';
import type { Dataset, NodeCatalogResponse, RegistryNode } from '../../../../shared/types';
import type { useWorkflowLayout } from '../../../_hooks/useWorkflowLayout';
import type { WorkflowViewport } from '../../../_model/graph';
import type { WorkflowComponentsController } from '../_features/components/_hooks/useWorkflowComponents';
import type { useAnalysisBoards } from '../_hooks/useAnalysisBoards';
import type { useRunHistory } from '../_hooks/useRunHistory';
import type { useWorkflowCanvasActions } from '../_hooks/useWorkflowCanvasActions';
import type { useWorkflowDocument } from '../_hooks/useWorkflowDocument';
import type { useWorkflowExecution } from '../_hooks/useWorkflowExecution';
import type { useWorkflowGraph } from '../_hooks/useWorkflowGraph';
export type WorkflowStageProps = {
    layout: ReturnType<typeof useWorkflowLayout>;
    graph: ReturnType<typeof useWorkflowGraph>;
    boards: ReturnType<typeof useAnalysisBoards>;
    runs: ReturnType<typeof useRunHistory>;
    canvas: ReturnType<typeof useWorkflowCanvasActions>;
    document: ReturnType<typeof useWorkflowDocument>;
    execution: ReturnType<typeof useWorkflowExecution>;
    components: WorkflowComponentsController;
    catalog: NodeCatalogResponse;
    datasets: Dataset[];
    columns: {
        availableColumns: string[];
        availableIdColumns: string[];
        inheritedIdColumn: string | null;
        availableRows: Array<Record<string, unknown>>;
    };
    message: string;
    paletteCollapsed: boolean;
    resultsCollapsed: boolean;
    analysisBoardOpen: boolean;
    workflowViewport: WorkflowViewport;
    onWorkflowViewportChange: (viewport: WorkflowViewport) => void;
    viewportStorageScope: string;
    setPaletteCollapsed: (value: SetStateAction<boolean>) => void;
    setResultsCollapsed: (value: SetStateAction<boolean>) => void;
    workflowDirtyForBoard: boolean;
    readOnly: boolean;
    onCreateCustomNode: () => void;
    onEditCustomNode: (node: RegistryNode) => void;
    onRefreshVersions: () => void;
    onRefreshComponents: () => void;
};
