import type { Run } from '../../../../shared/types';
import { MAIN_ANALYSIS_BOARD_ID } from '../../../_model/graph';
import { RightPanel } from './RightPanel';
import type { WorkflowStageProps } from './workflowStageTypes';
export function WorkflowRightSidebar({ resultRun, ...p }: WorkflowStageProps & {
    resultRun: Run | null;
}) {
    return <RightPanel floatingRightStyle={p.layout.floatingRightStyle} resultsCollapsed={p.resultsCollapsed} setResultsCollapsed={p.setResultsCollapsed} startResize={p.layout.startResize} selectedFlow={p.graph.selectedFlow} runHistory={p.runs.runHistory} currentRun={p.runs.currentRun} resultRun={resultRun} busy={p.runs.busy} retryRun={p.execution.retryRun} cancelRun={p.runs.cancelRun} selectHistoricalRun={p.runs.selectHistoricalRun} refreshRunHistory={p.runs.refreshRunHistory} selectedNode={p.graph.selectedNode} selectedEdge={p.graph.selectedEdge} registry={p.catalog.nodes} aliases={p.catalog.aliases} datasets={p.datasets} availableColumns={p.columns.availableColumns} availableIdColumns={p.columns.availableIdColumns} inheritedIdColumn={p.columns.inheritedIdColumn} availableRows={p.columns.availableRows} updateNodeParams={p.canvas.updateNodeParams} renameNode={p.canvas.renameNode} deleteSelected={p.graph.deleteSelected} onUngroupComponent={p.components.setConfirmUngroup} selectedId={p.graph.selectedId} onAddOutputToBoard={p.boards.addOutputFromResults} analysisBoardOpen={p.analysisBoardOpen} boardTabs={p.boards.boards} boardTargetId={p.analysisBoardOpen ? p.boards.targetBoardId : MAIN_ANALYSIS_BOARD_ID} onBoardTargetChange={p.boards.selectBoard} workflowId={p.document.currentWorkflowId} workflowVersions={p.document.workflowVersions} selectedVersionId={p.document.selectedVersionId} versionPreviewActive={p.readOnly} onSelectVersion={p.document.viewVersion} onRestoreVersion={p.document.restoreVersion} onDeleteVersion={p.document.deleteVersion} onRefreshVersions={p.onRefreshVersions} onReturnToCurrentVersion={p.document.returnToCurrentVersion} components={p.components.items} onRefreshComponents={p.onRefreshComponents} onEditComponent={(component) => { if (component.current_version)
        void p.components.enterEditor(component, component.current_version); }} onManageComponentVersions={p.components.openVersionManager} onExportComponent={p.components.exportPackage} onArchiveComponent={p.components.archive} onDeleteComponent={p.components.setConfirmDelete} onImportComponent={p.components.importPackage} readOnly={p.readOnly}/>;
}
