import type { Dispatch, SetStateAction } from 'react';
import type { Edge, Node } from '@xyflow/react';
import type { Dataset, NodeCatalogResponse, Run, RunSummary, WorkflowVersion } from '../../../../../shared/types';
import type { AnalysisBoardTab } from '../../../../_model/board';
import type { WorkflowViewport } from '../../../../_model/graph';
export type UseWorkflowDocumentOptions = {
    projectId: number;
    initialWorkflowId: number | null;
    catalog: NodeCatalogResponse;
    setCatalog: Dispatch<SetStateAction<NodeCatalogResponse>>;
    nodes: Node[];
    setNodes: Dispatch<SetStateAction<Node[]>>;
    edges: Edge[];
    setEdges: Dispatch<SetStateAction<Edge[]>>;
    clearSelection: () => void;
    datasetId: number | null;
    setDatasetId: Dispatch<SetStateAction<number | null>>;
    refreshDatasets: () => Promise<Dataset[]>;
    targetColumn: string;
    setTargetColumn: Dispatch<SetStateAction<string>>;
    taskType: string;
    setTaskType: Dispatch<SetStateAction<string>>;
    restoreWorkflowCanvasViewport: (viewport: WorkflowViewport) => void;
    serializedBoards: AnalysisBoardTab[];
    analysisBoardSignature: unknown;
    activeBoardId: string;
    restoreBoards: (boards: AnalysisBoardTab[], activeBoardId: string) => void;
    setBoardOpen: (open: boolean) => void;
    workflowLastRunId: number | null;
    setWorkflowLastRunId: Dispatch<SetStateAction<number | null>>;
    setCurrentRun: Dispatch<SetStateAction<Run | null>>;
    setNodeStateRun: Dispatch<SetStateAction<Run | null>>;
    setRunHistory: Dispatch<SetStateAction<RunSummary[]>>;
    setLastRunSignature: Dispatch<SetStateAction<string>>;
    autosavePaused: boolean;
    versionPreview: WorkflowVersion | null;
    setVersionPreview: Dispatch<SetStateAction<WorkflowVersion | null>>;
    setMessage: (message: string) => void;
};
