import { ArrowDown, ArrowUp, Trash2 } from 'lucide-react';
import type { ComponentBoundaryPort } from '../../../shared/types';
const TYPES = ['any', 'dataframe', 'json', 'json_items', 'model', 'metrics', 'plot', 'file', 'report', 'artifact_ref', 'text', 'schema'];
function reorder<T>(items: T[], index: number, offset: number) { const target = index + offset; if (target < 0 || target >= items.length)
    return items; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; return next; }
export function InterfaceRows({ title, ports, onChange }: {
    title: string;
    ports: ComponentBoundaryPort[];
    onChange: (ports: ComponentBoundaryPort[]) => void;
}) { return <section className="component-definition-section"><header><b>{title}</b><small>{ports.length} پورت عمومی</small></header>{ports.map((port, index) => <div className="component-interface-row" key={port.id}><div className="component-interface-order"><button type="button" className="workflow-tab-icon-button" disabled={!index} onClick={() => onChange(reorder(ports, index, -1))}><ArrowUp size={13}/></button><button type="button" className="workflow-tab-icon-button" disabled={index === ports.length - 1} onClick={() => onChange(reorder(ports, index, 1))}><ArrowDown size={13}/></button></div><label><span>نام</span><input value={port.name} onChange={(e) => onChange(ports.map((item, i) => i === index ? { ...item, name: e.target.value } : item))}/></label><label><span>نوع</span><select value={port.type} onChange={(e) => onChange(ports.map((item, i) => i === index ? { ...item, type: e.target.value } : item))}>{TYPES.map((type) => <option key={type} value={type}>{type}</option>)}</select></label><label className="component-interface-required"><input type="checkbox" checked={port.required} onChange={(e) => onChange(ports.map((item, i) => i === index ? { ...item, required: e.target.checked } : item))}/> الزامی</label><button type="button" className="workflow-tab-icon-button workflow-version-delete" onClick={() => onChange(ports.filter((_, i) => i !== index))}><Trash2 size={14}/></button></div>)}{!ports.length && <div className="empty-state small">هیچ پورت عمومی برای این سمت منتشر نشده است.</div>}</section>; }
