import type { CSSProperties, Dispatch, PointerEvent as ReactPointerEvent, SetStateAction } from 'react';
import type { Edge, Node } from '@xyflow/react';
import type { AnalysisBoardTab } from '../../../../_model/board';
import type { Output } from '../../../../../features/results/components/ResultsPanel';
import type { Dataset, RegistryNode, Run, RunSummary, WorkflowComponent, WorkflowVersionSummary } from '../../../../../shared/types';
export type RightTab = 'results' | 'settings' | 'history' | 'assistant' | 'versions' | 'components';
export type RightPanelProps = {
    floatingRightStyle: CSSProperties;
    resultsCollapsed: boolean;
    setResultsCollapsed: Dispatch<SetStateAction<boolean>>;
    startResize: (event: ReactPointerEvent<HTMLDivElement>) => void;
    selectedFlow: {
        nodes: Node[];
        edges: Edge[];
        mode: 'all' | 'selected';
    };
    runHistory: RunSummary[];
    currentRun: Run | null;
    resultRun: Run | null;
    busy: boolean;
    retryRun: (run: Run | RunSummary) => void | Promise<void>;
    cancelRun: (run: Run | RunSummary) => void | Promise<void>;
    selectHistoricalRun: (run: RunSummary) => void | Promise<void>;
    refreshRunHistory: () => Promise<void>;
    selectedNode: Node | null;
    selectedEdge: Edge | null;
    registry: RegistryNode[];
    aliases: Record<string, string>;
    datasets: Dataset[];
    availableColumns: string[];
    availableIdColumns?: string[];
    inheritedIdColumn?: string | null;
    availableRows?: Record<string, unknown>[];
    updateNodeParams: (nodeId: string, params: Record<string, unknown>) => void;
    renameNode: (nodeId: string, label: string) => void;
    deleteSelected: () => void;
    onUngroupComponent: (node: Node) => void;
    selectedId: string | null;
    onAddOutputToBoard?: (output: Output, index: number) => void;
    analysisBoardOpen: boolean;
    boardTabs: AnalysisBoardTab[];
    boardTargetId: string;
    onBoardTargetChange: (id: string) => void;
    workflowId: number | null;
    onAssistantWorkflowChanged?: () => void | Promise<void>;
    workflowVersions: WorkflowVersionSummary[];
    selectedVersionId: number | null;
    versionPreviewActive: boolean;
    onSelectVersion: (version: WorkflowVersionSummary) => void;
    onRestoreVersion: (version: WorkflowVersionSummary) => void;
    onDeleteVersion: (version: WorkflowVersionSummary) => void;
    onRefreshVersions: () => void;
    onReturnToCurrentVersion: () => void;
    components: WorkflowComponent[];
    onRefreshComponents: () => void;
    onEditComponent: (component: WorkflowComponent) => void;
    onManageComponentVersions: (component: WorkflowComponent) => void;
    onExportComponent: (component: WorkflowComponent) => void;
    onArchiveComponent: (component: WorkflowComponent) => void;
    onDeleteComponent: (component: WorkflowComponent) => void;
    onImportComponent: (payload: Record<string, unknown>) => void;
    readOnly: boolean;
};
